### ISSUE TITLE
Right curly bracket showing at bottom of new_base.html

### ISSUE THREAD

**Issue by jarmoza** [metaneuro/concept_query#103]
There is an errant right curly bracket `}` showing at the bottom left of the query_interface/form page.

**Comment by jarmoza** [comment]
See: https://github.com/metaneuro/concept_query/commit/222da80fb99733463f1526ca7558575384db9cf6

**Comment by jarmoza** [comment]
@surchs I say let's just merge this and we can open up another PR for cleanup when we want to address.

**Comment by jarmoza** [comment]
Closed with https://github.com/metaneuro/concept_query/pull/106

**Comment by surchs** [comment]
@jarmoza was this intentionally re-opened? What remains to be done here?

**Comment by jarmoza** [comment]
@surchs I think this is a mistaken reopening. Can you confirm? It may take me longer as my new laptop is not yet fully setup for running the project code.
