### ISSUE TITLE
Resolve issue of clashing pipfile.lock files

### ISSUE THREAD

**Issue by jarmoza** [metaneuro/concept_query#28]
This issue is linked to #59

**Comment by surchs** [comment]
Do we have any good new ideas here @jarmoza ?

**Comment by jarmoza** [comment]
To summarize the discussion of this issue from Slack:

The issue with the `Pipfile.lock` merge conflict has to do with developers working across platforms. (In this case @surchs on Linux and @jarmoza on MacOS.) This results in different hashes created in the lockfile for the various package (versions) to be installed.

The solution to this issue is to have users/developers use the `pipenv lock` command before installing packages to ensure they have no conflicts created via the operating system of who last committed the `Pipfile.lock` file and the user/developer's respective, potentially different operating system.

```
git clone https://github.com/metaneuro/concept_query.git
cd concept_query
pipenv lock
pipenv shell
pipenv install
pipenv install -d
```

The last command (`pipenv install -d`) is only necessary for developers.

The resolution was listed here via pipenv developer Nate Prewitt: [](https://github.com/pypa/pipenv/issues/210)
