### ISSUE TITLE
Change URL routing to reflect the app structure better

### ISSUE THREAD

**Issue by jarmoza** [metaneuro/concept_query#37]
Determine what if any changes to routing for the django query_prototype app should be done for the demo and into the future

**Comment by jarmoza** [comment]
Root should go to interface. And /admin to admin interface.

@surchs Sound good?

**Comment by surchs** [comment]
Agreed, root should go to the interface! 

> Also, this may include the implementation of a query string for SPARQL queries

what do you mean by that @jarmoza ?

**Comment by jarmoza** [comment]
A query string in the browser bar that reflects the fields being sent to the graphdb - that can be saved by user for future use

**Comment by surchs** [comment]
oh yeah, I think that'd be very nice. We should look up how that would be implemented.

**Comment by jarmoza** [comment]
Closed by https://github.com/metaneuro/concept_query/pull/107
