### ISSUE TITLE
set up and configure circleCI

### ISSUE THREAD

**Issue by surchs** [metaneuro/concept_query#67]
We want to have a setup that:
- [ ] automatically runs the `pytest` unittest suite for each new PR on github
- [ ] gives us an overview of passed or failed test status inside GH

**Comment by jarmoza** [comment]
Github Checks for CircleCI is now enabled. We'll be able to see CircleCI workflow messaging under each PR's 'Checks' tab.

![image](https://user-images.githubusercontent.com/4140162/144912399-fafe75da-0277-423d-a6c6-32e2e9e1a390.png)

**Comment by jarmoza** [comment]
PR for this issue has been merged. https://github.com/metaneuro/concept_query/pull/102
