### ISSUE TITLE
dockerize django app

### ISSUE THREAD

**Issue by surchs** [metaneuro/concept_query#68]
We want the django app to be runnable on the CircleCI server to run our continuous tests.

- [x] figure out what config files are needed to create a dockerized django app
- [x] write the docker compose or Dockerfile or reuse a template one
- [x] make sure the server is runnable locally
- [x] read through the CircleCI config to make the docker container runnable for CircleCI (if that requires additional config, see #67)
- [ ] document what you have learned about the dockerization on GDrive

**Comment by jarmoza** [comment]
Tool is successfully dockerized, but will not be needed until deployment. Below is the Dockerfile for building the image.

```
# FROM python:3.9-slim-buster
FROM python:3
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Working directory
WORKDIR /concept_query

# Creating folders, and files for a project:
COPY . /concept_query

# System deps:
RUN /usr/local/bin/python -m pip install --upgrade pip
RUN pip install -r requirements.txt

# Django migrations
RUN python manage.py makemigrations
RUN python manage.py migrate

# Django static files
# This should be done by developers during commit and not during container setup
# RUN python manage.py collectstatic

# Start Django server
CMD ["python", "manage.py", "runserver", "0.0.0.0:9000"]
```
