### ISSUE TITLE
Set up continuous integration

### ISSUE THREAD

**Issue by surchs** [metaneuro/concept_query#81]
We want to have a setup that:
- [ ] automatically runs the `pytest` unittest suite for each new PR on github
- [ ] gives us an overview of passed or failed test status inside GH

**Comment by surchs** [comment]
closing as duplicate of #67

**Comment by jarmoza** [comment]
Github Checks for CircleCI is now enabled. We'll be able to see CircleCI workflow messaging under each PR's 'Checks' tab.

![image](https://user-images.githubusercontent.com/4140162/144911983-ac0e7a37-290f-4f72-981a-9882dd0d8a28.png)
